version: '3.1'

services:
  mongo:
    image: mongo
    container_name: nodes-users-db
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/plaad-dev:/data/db
